import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Lato } from "next/font/google";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nirmal S.M.",
  description: "Generated by create next app",
};
const lato = Lato({
  subsets: ["latin"],
  weight: '100'
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${lato.className}`}
      >
        {children}
      </body>
    </html>
  );
}
